/**
 * What each individual field means.
 *
 * Keys are lowercase field names. A key may be scoped to a section as
 * `section::field` where the same name means different things in two places.
 * Anything not listed here falls back to the pattern list in `glossary.ts`.
 */
export const FIELD_NOTES: Record<string, string> = {
  /* ── HTTP request headers ─────────────────────────────────── */
  accept: "The content types this request will accept, in preference order. The exact list and its quality values differ between browsers and versions.",
  "accept-encoding": "Which compression formats the browser can decode. Support for the newest one, zstd, indicates a recent Chromium build.",
  "accept-language": "Your languages in ranked order, with quality values. Sent on every request, and one of the strongest signals of where you are from.",
  connection: "Whether the underlying TCP connection should be kept open for further requests.",
  cookie: "Every cookie this site has previously stored, returned automatically before any script runs.",
  host: "The hostname you typed or clicked. Distinct from the server's own name when a proxy or CDN sits in front.",
  "sec-fetch-dest": "What the browser intends to do with the response: a document, an image, a script. Lets a server reject requests that arrive in the wrong context.",
  "sec-fetch-mode": "How the request was made — a navigation, a same-origin fetch, a CORS request.",
  "sec-fetch-site": "The relationship between the requesting page and this one: none for a typed URL, same-origin, same-site or cross-site.",
  "sec-fetch-user": "Present only when a genuine user gesture caused the navigation, rather than a script.",
  "upgrade-insecure-requests": "Signals the browser would rather be redirected to HTTPS than load mixed content.",
  "user-agent": "The browser's self-description. Frozen and reduced in modern browsers, but still the value most detection is built on.",
  "x-forwarded-for": "The client address as recorded by a proxy. On a public site this is what gets resolved to a city and an internet provider.",
  "x-forwarded-host": "The hostname the client originally requested, preserved by the proxy.",
  "x-forwarded-port": "The port the client originally connected to.",
  "x-forwarded-proto": "Whether the original request was HTTP or HTTPS, before the proxy forwarded it.",

  /* ── Client hints ─────────────────────────────────────────── */
  "device-memory": "Approximate RAM in gibibytes, rounded to a power of two and capped at 8 so it cannot pinpoint a machine on its own.",
  downlink: "Estimated downstream bandwidth in megabits per second, rounded to the nearest 25 kbps.",
  ect: "Effective connection type: slow-2g, 2g, 3g or 4g, derived from observed round-trip times rather than the actual radio.",
  rtt: "Estimated round-trip time in milliseconds, rounded to 25 ms. A rough measure of distance to the server.",
  "sec-ch-dpr": "Device pixel ratio: how many physical pixels make up one CSS pixel.",
  "sec-ch-prefers-color-scheme": "Whether your operating system is set to light or dark, sent with the request so the first paint can match.",
  "sec-ch-prefers-reduced-motion": "Whether you have asked the system to reduce animation, sent before any script runs.",
  "sec-ch-prefers-reduced-transparency": "Whether you have asked the system to reduce transparency effects.",
  "sec-ch-ua": "The browser's brand list, deliberately including a fake brand to stop servers hard-coding exact strings.",
  "sec-ch-ua-arch": "Processor architecture, such as arm or x86 — which names the silicon generation of your machine.",
  "sec-ch-ua-bitness": "Whether the browser binary is 64-bit or 32-bit.",
  "sec-ch-ua-form-factors": "The shape of the device: Desktop, Mobile, Tablet, Watch, XR, eReader or Automotive.",
  "sec-ch-ua-full-version": "The complete browser version, down to the patch number.",
  "sec-ch-ua-full-version-list": "Every brand in the browser's identity with its full version, the precise replacement for the user-agent string.",
  "sec-ch-ua-mobile": "A boolean for whether this is a mobile device, sent as ?1 or ?0.",
  "sec-ch-ua-model": "The device model, populated on Android and empty on desktop.",
  "sec-ch-ua-platform": "The operating system family, as a quoted string.",
  "sec-ch-ua-platform-version": "The operating system version, which on macOS and Windows narrows down when the machine was last updated.",
  "sec-ch-ua-wow64": "Whether a 32-bit browser is running on 64-bit Windows. Kept only so client hints can reproduce the old user-agent string exactly.",
  "sec-ch-viewport-height": "The height in CSS pixels of the area the page will be drawn into.",
  "sec-ch-viewport-width": "The width in CSS pixels of the area the page will be drawn into, sent before the page loads so images can be sized.",

  /* ── Connection ───────────────────────────────────────────── */
  "http version": "The protocol version negotiated for this request. HTTP/2 and /3 multiplex, which changes how requests are ordered and timed.",
  transport: "Whether the connection is encrypted. Over TLS the handshake itself carries a further fingerprint, which this page does not collect.",
  "remote address": "The peer address of the socket carrying this request, read below the HTTP layer.",
  "remote port": "The ephemeral source port. New for each connection, so it identifies the connection rather than you.",
  "address family": "IPv4 or IPv6. Which one you arrive on often says something about your provider.",
  "local (server) address": "The address and port this server is listening on.",
  "requests on this tcp connection": "How many requests have reused this connection. Keep-alive means one connection carries many requests.",
  "bytes read on socket": "Total bytes received on this socket, including the request headers themselves.",
  "header count": "How many headers the browser sent. The number alone separates browser families.",
  "raw header order": "The exact sequence the browser emitted its headers in. Each engine has its own fixed order, so this betrays the real browser even if the user-agent string is edited.",
  "request line": "The method and path of the request, as written on the wire.",

  /* ── Server-derived ───────────────────────────────────────── */
  "client ip (x-forwarded-for)": "The address a public site would resolve to a city, an internet provider and often an employer.",
  "proxy chain": "Every proxy that added itself to the forwarding header, in order.",
  "x-real-ip": "An alternative address header set by some proxies.",
  "host requested": "The hostname in the request. Here it decides which origin the third-party frame uses.",
  "ua length": "Length of the user-agent string. Reduced user agents are near 110 characters; longer ones usually mean an older or embedded browser.",
  "accept-language (raw)": "The unparsed header, including the quality values that rank your languages.",
  "preferred language": "The first entry in your language list — your primary language.",
  "language count": "How many languages your browser advertises. Most people send one or two; more is distinctive.",
  "dnt header": "The Do Not Track header. Voluntary, widely ignored, and now removed from most browsers.",
  "sec-gpc header": "Global Privacy Control, a successor to Do Not Track that carries legal weight in several US states.",
  referer: "The page you were on immediately before this one, sent to the new site by default.",
  priority: "The browser's requested priority for this resource, part of newer HTTP prioritization.",
  "cookies sent": "How many cookies came back with this request.",
  "cookie names": "The names of the cookies returned, without their values.",
  "cookie bytes": "Total size of the cookie header. Large values suggest a site storing a lot of state about you.",
  "server time (utc)": "The server's clock at the moment of this request.",
  "server epoch ms": "Server time in milliseconds. Comparing it with your own clock measures your drift, which is itself a weak identifier.",
  "server uptime": "How long this server process has been running.",
  "server timezone": "The timezone of the machine serving this page, for contrast with yours.",
  runtime: "The server's Node version, platform and processor architecture.",

  /* ── Visitor identifier ───────────────────────────────────── */
  visitorid: "The composite identifier: dozens of weak signals reduced to one value that usually survives cookie clearing and private windows.",
  "confidence.score": "The library's own estimate, from 0 to 1, of how likely this identifier is correct for a returning visitor.",
  "confidence.comment": "The vendor's note about the score, including its upsell for the commercial version.",
  version: "The version of the fingerprinting library that produced the identifier.",
  "components collected": "How many separate entropy sources fed the identifier.",
  "debug string length": "Size of the full component dump, a rough measure of how much was sampled.",

  /* ── Rendering fingerprints ───────────────────────────────── */
  "canvas 2d hash": "A digest of pixels produced by drawing the same text and shapes on every visitor's machine. Font rasterization and anti-aliasing differ enough to identify.",
  "canvas 2d data length": "Byte length of the encoded image. It shifts with rendering differences and is a cheap secondary signal.",
  "webgl render hash": "A digest of a small scene drawn on the GPU, capturing driver-level differences invisible on screen.",
  "audio dsp hash": "A digest of an inaudible tone processed through a compressor. Floating-point behavior in the audio stack varies by platform.",
  "math/engine hash": "A digest of transcendental math results. Different engines and CPUs round differently in the last bits.",
  "installed-font hash": "A digest of exactly which probed fonts resolved, standing in for the list itself.",

  /* ── Persistence ──────────────────────────────────────────── */
  "assigned identifier": "The identifier this page is keeping for you across visits, written to every store at once.",
  status: "Whether the identifier was newly minted this visit or recovered from an earlier one.",
  "recovered from": "Which stores still held a copy. Any single survivor is enough to restore all the others.",
  "storage mechanisms written": "How many independent stores now hold the identifier. Each is cleared by a different control.",
  "cookie copy (before)": "The value found in cookies at the start of this visit.",
  "localstorage copy (before)": "The value found in localStorage, which survives a cookie-only clear.",
  "sessionstorage copy (before)": "The value found in sessionStorage, which is emptied when the tab closes.",
  "indexeddb copy (before)": "The value found in the IndexedDB database, a store many people never think to clear.",
  "cache storage copy (before)": "The value found in Cache Storage, intended for offline assets and equally usable as an identifier.",
  "service worker copy (before)": "The value held by the registered service worker, which persists after the tab is closed.",
  "window.name copy (before)": "The value held in the tab's name, which follows the tab rather than the site.",
  "http cache (etag) identifier": "A unique label the server attached to a cached response. Your browser hands it back on every revalidation, so it is not cleared with site data.",
  "server has revalidated this etag": "How many times the browser has returned that label, each one proving continuity of the same cache.",
  "etag first issued": "When the server first minted the cache identifier.",
  "visit count": "How many times this browser has loaded the page, counted in local storage.",
  "first seen": "The timestamp of the earliest visit still recorded.",
  "all copies now rewritten": "Confirms the identifier was written back to every store, completing the respawn.",

  /* ── Tamper and automation ────────────────────────────────── */
  "function.prototype.bind": "Checks a core built-in still reports as native code. Rewritten built-ins are a hallmark of anti-detect tooling.",
  "navigator.permissions.query": "Spoofing tools often patch this to fake permission states; the patch is visible in the function's source.",
  "htmlcanvaselement.todataurl": "The function canvas fingerprinting depends on. Privacy extensions replace it to add noise.",
  "canvasrenderingcontext2d.getimagedata": "The other half of canvas fingerprinting, patched by the same extensions.",
  "webglrenderingcontext.getparameter": "Used to read GPU strings; replaced by tools that want to fake the graphics hardware.",
  "audiobuffer.getchanneldata": "The function audio fingerprinting reads, patched by tools that randomize audio output.",
  "date.prototype.gettimezoneoffset": "Patched when a tool wants to fake the timezone without changing the system clock.",
  "navigator.mediadevices.enumeratedevices": "Patched to hide or invent cameras and microphones.",
  "navigator.useragent descriptor": "Whether the user agent is still an inherited accessor. An own property on the instance means it was overwritten.",
  "navigator.webdriver": "True when the browser is under automated control, which browsers report honestly by design.",
  "automation globals found": "Globals left behind by automation frameworks such as Selenium, Puppeteer, Playwright or PhantomJS.",
  "chromedriver artefacts": "Properties ChromeDriver injects into the document, a direct sign of automation.",
  "ua vs platform consistency": "Whether the platform the user agent claims matches the one the rest of the browser reports.",
  "languages list empty": "An empty language list is nearly impossible for a real user and a classic headless tell.",
  "plugins empty on chromium": "Chromium normally reports a fixed set of PDF plugins; an empty list suggests a stripped or automated build.",
  "notification permission anomaly": "Headless browsers historically reported denied notifications while lacking the Permissions API, an inconsistency real browsers do not have.",
  "prototype chain depth (navigator)": "How deep the navigator object's inheritance runs. Wrapping it in a proxy changes the depth.",
  "tostring tag of window": "The internal class name of the global object, which differs in some automation environments.",
  "iframe contentwindow reachable": "Whether a fresh iframe reports the same user agent as its parent. Tools that patch only the top window disagree here.",

  /* ── Privacy posture ──────────────────────────────────────── */
  "private/incognito mode": "Whether this is a private window, inferred from the storage restrictions private mode imposes.",
  "browser identified as": "Which browser the incognito heuristics matched, since each one leaks private mode differently.",
  "do not track": "The legacy opt-out signal. Sites were free to ignore it and almost all did.",
  "global privacy control": "A legally recognized opt-out signal in several US states, unlike Do Not Track.",
  "cookies enabled": "Whether this browser will store cookies at all.",
  "third-party cookie writes": "Whether a cookie marked SameSite=None was accepted, which is what cross-site tracking depends on.",
  "ad/tracker blocker present": "Whether decoy elements named after blocklist targets were removed from the page.",
  "storage partitioned": "Whether the browser exposes the Storage Access API, the mechanism that separates an embedded site's storage per top-level site.",
  "timezone vs language mismatch": "A region in your language tag that disagrees with your timezone can indicate a VPN.",
  "screen dimensions rounded": "Suspiciously round screen dimensions suggest letterboxing or a spoofed resolution rather than real hardware.",
  "reduced timer precision": "How finely the clock can be read. Coarsened timers indicate anti-fingerprinting measures are active.",
  "canvas readback noise": "Whether two identical drawings produce identical pixels. Differences mean the browser is randomizing canvas output.",
  "webgl software renderer": "Whether rendering runs on real hardware or a software rasterizer, which usually means a virtual machine or headless browser.",

  /* ── Navigator ────────────────────────────────────────────── */
  "navigator::useragent": "The full self-description string. Everything after 'Mozilla/5.0' is historical fiction kept for compatibility.",
  appversion: "The user-agent string minus its first token. Retained only for scripts written in the 1990s.",
  appname: "Frozen to 'Netscape' in every browser, so it identifies nothing.",
  appcodename: "Frozen to 'Mozilla' in every browser, another fossil of the first browser war.",
  "navigator::platform": "The operating system and CPU family. Deprecated, still widely read, and cross-checked here against the user agent.",
  "navigator::product": "Frozen to 'Gecko' everywhere, regardless of the real engine.",
  productsub: "Build identifier: '20030107' in Chromium and Safari, the actual build date in Firefox. A quiet way to separate engines.",
  "navigator::vendor": "'Google Inc.' in Chromium, 'Apple Computer, Inc.' in Safari, empty in Firefox. One of the cleanest engine tells.",
  vendorsub: "Empty in every current browser; kept for compatibility.",
  oscpu: "The operating system and architecture, reported only by Firefox. Its presence alone identifies the engine.",
  buildid: "Firefox's build identifier, frozen to a constant to stop it identifying individual installs.",
  "navigator::language": "Your primary language, which the page uses and every server sees.",
  "navigator::languages": "Your full language list in preference order, a higher-entropy signal than the primary language alone.",
  "navigator::online": "Whether the browser believes it has a network connection. It only means an interface is up, not that anything is reachable.",
  cookieenabled: "Whether cookie storage is permitted for this site.",
  donottrack: "The Do Not Track preference as the page sees it, distinct from the header the server receives.",
  globalprivacycontrol: "The GPC opt-out as visible to scripts.",
  "navigator::hardwareconcurrency": "Logical processor count, including hyperthreads. Not rounded, so it is an unusually sharp hardware signal.",
  "navigator::devicememory": "Approximate RAM in gibibytes, rounded to a power of two and capped at 8.",
  maxtouchpoints: "How many simultaneous touches the screen supports. Zero means no touchscreen.",
  pdfviewerenabled: "Whether the browser can display PDFs itself. Part of the fixed plugin story modern browsers report.",
  webdriver: "Set by browsers under automated control. Honest by specification, which is why automation tools try to hide it.",
  "javaenabled()": "Always false now. Kept because old scripts still call it.",
  "useractivation.isactive": "Whether a user gesture is in effect right now, which gates actions like opening a window.",
  "useractivation.hasbeenactive": "Whether this page has ever received a genuine gesture. False on a page you have not touched.",
  "plugins.length": "Number of plugins. Chromium reports a fixed list of five PDF entries; Firefox reports none.",
  plugins: "The plugin names themselves. Once a rich fingerprint, now standardized to remove that entropy.",
  "mimetypes.length": "Number of MIME types the plugin list claims to handle.",
  mimetypes: "The MIME types themselves, in practice only the PDF pair.",

  /* ── Parsed user agent ────────────────────────────────────── */
  "browser.name": "The browser inferred from the user-agent string, the way analytics platforms infer it.",
  "browser.version": "The version claimed in the string, which the reduced user agent rounds off.",
  "browser.major": "Just the major version, which is what most compatibility checks use.",
  "engine.name": "The rendering engine: Blink, Gecko or WebKit.",
  "engine.version": "The engine version, usually tracking the browser version in Chromium.",
  "os.name": "The operating system inferred from the string.",
  "os.version": "The OS version claimed. Modern browsers freeze this — macOS has reported 10.15.7 for years.",
  "device.vendor": "Hardware maker, inferred from the string and generally only populated on mobile.",
  "device.model": "Device model where the string carries one; Android sends it, desktops do not.",
  "device.type": "Device category. Empty means desktop by convention, which is why it is shown as implied.",
  "cpu.architecture": "Processor architecture where the string mentions it; usually absent in reduced user agents.",
  "ua string parsed": "The exact input all of the above was inferred from.",

  /* ── UA client hints (script side) ────────────────────────── */
  useragentdata: "Whether the structured client-hints API exists, which in itself identifies a Chromium browser.",
  brands: "The brand list with major versions, including the intentionally fake brand.",
  mobile: "Whether the browser considers this a mobile device.",
  "ua-client-hints::platform": "Operating system family, as reported by the structured API rather than the string.",
  "highentropy.architecture": "Processor architecture, given only when a page asks for it explicitly.",
  "highentropy.bitness": "Whether the browser binary is 64-bit.",
  "highentropy.model": "Device model, populated on Android.",
  "highentropy.platformversion": "Operating system version, precise enough to say which update you are on.",
  "highentropy.uafullversion": "Complete browser version including patch number.",
  "highentropy.fullversionlist": "Every brand with its full version, the highest-fidelity identity the browser will give.",
  "highentropy.wow64": "Whether a 32-bit browser is running on 64-bit Windows.",
  "highentropy.formfactors": "The device shape, such as Desktop, Mobile or XR.",

  /* ── JavaScript engine ────────────────────────────────────── */
  "typeerror message style": "Engines word the same error differently. V8, SpiderMonkey and JavaScriptCore each have a distinct phrasing.",
  "error.stack format": "Stack trace formatting differs per engine, another tell that survives user-agent spoofing.",
  "error.capturestacktrace": "A V8-only helper. Its presence means Chromium or Node.",
  "function.tostring of native": "How the engine prints a built-in function. The exact spacing differs between engines.",
  "0.1 + 0.2": "The classic floating-point result. Identical everywhere, and useful as a control against faked values.",
  "number.max_safe_integer": "The largest exactly representable integer, identical in every conforming engine.",
  "tofixed rounding (1.005)": "Rounding behavior at the edge of floating-point precision, which has differed between engines historically.",
  "array.sort stability marker": "Sort behavior, now standardized as stable but a useful check for older or unusual engines.",
  "intl present": "Whether internationalization support is compiled in. Some stripped builds omit it.",
  bigint: "Support for arbitrary-precision integers, which dates the engine.",
  weakref: "Support for weak references, added in 2020. Presence narrows the version range.",
  finalizationregistry: "Garbage-collection callbacks, shipped alongside WeakRef.",
  structuredclone: "The global deep-clone function, added in 2021.",
  sharedarraybuffer: "Shared memory between threads. Only available when the page is cross-origin isolated, so its absence is usually a security header rather than an old browser.",
  atomics: "Atomic operations on shared memory, paired with SharedArrayBuffer.",
  webassembly: "Whether WebAssembly is available at all.",
  "wasm simd": "Whether WebAssembly SIMD instructions validate, which dates the engine and the hardware.",
  "eval allowed (csp)": "Whether the page's Content Security Policy permits dynamic code. This page allows it; many do not.",
  "globalthis keys": "How many properties hang off the global object. The count shifts with browser version and with injected extensions.",
  "tosource (firefox)": "A Firefox-only method. Its presence identifies Gecko outright.",
  "chrome object": "The window.chrome object present in Chromium browsers, and a common thing for automation to fake.",
  "window.safari": "A Safari-only global.",
  "process/electron": "Node's process object leaking into the page, which means this is an Electron app rather than a browser.",

  /* ── Fonts ────────────────────────────────────────────────── */
  "fonts probed": "How many typefaces were tested by measuring text width.",
  "fonts detected": "How many of them are installed. The count alone splits the population; the exact set is far sharper.",
  "detected list": "Which probed fonts resolved. Installed fonts follow the software you own, so this reads like a software inventory.",
  "not detected": "Which probed fonts are absent, which is equally informative.",
  "document.fonts.size": "How many web fonts this page itself loaded, as opposed to system fonts.",
  "document.fonts.status": "Whether the page's own fonts have finished loading.",
  "queryLocalFonts API": "Whether the browser offers the permission-gated API that returns the real font list. Chromium does; Firefox and Safari refuse to implement it.",

  /* ── Screen and viewport ──────────────────────────────────── */
  "screen.width": "Full display width in CSS pixels, independent of the browser window.",
  "screen.height": "Full display height in CSS pixels.",
  "screen.availwidth": "Width minus space reserved by the system, such as a dock.",
  "screen.availheight": "Height minus the menu bar and taskbar, which reveals where those bars sit.",
  "screen.availleft": "Left edge of the usable area. Non-zero usually means a vertical dock or a second monitor to the left.",
  "screen.availtop": "Top edge of the usable area, which exposes the height of a menu bar.",
  "screen.colordepth": "Bits per pixel the display reports, almost always 24 or 30.",
  "screen.pixeldepth": "Colour depth again, kept as a separate legacy property.",
  "screen.isextended": "Whether more than one display is attached, readable without the multi-screen permission.",
  "screen.orientation.type": "Portrait or landscape, and whether it is the primary or secondary orientation.",
  "screen.orientation.angle": "Rotation in degrees from the device's natural orientation.",
  devicepixelratio: "Physical pixels per CSS pixel. Values like 2 or 3 mean a high-density display; fractional values usually mean browser zoom.",
  "window.outerwidth": "Width of the whole browser window, including its frame.",
  "window.outerheight": "Height of the whole window, including toolbars.",
  "window.innerwidth": "Width of the page area itself, which is what layout responds to.",
  "window.innerheight": "Height of the page area, excluding browser chrome.",
  "window.screenx": "Horizontal position of the window on the desktop, which hints at your monitor arrangement.",
  "window.screeny": "Vertical position of the window on the desktop.",
  "chrome height (outer-inner)": "The vertical space taken by browser interface. An unusually large gap is the classic way to detect open developer tools.",
  "documentelement.clientwidth": "Layout viewport width, excluding any scrollbar.",
  "documentelement.clientheight": "Layout viewport height, excluding horizontal scrollbars.",
  "visualviewport.width": "Width of what is actually visible, which differs from the layout viewport when you pinch-zoom.",
  "visualviewport.height": "Visible height, which shrinks when a mobile keyboard opens.",
  "visualviewport.scale": "Current pinch-zoom factor.",
  "visualviewport.offsetleft": "Horizontal offset of the visual viewport within the layout viewport while zoomed.",
  "visualviewport.offsettop": "Vertical offset of the visual viewport while zoomed.",
  "visualviewport.pageleft": "Horizontal scroll position of the visual viewport within the document.",
  "visualviewport.pagetop": "Vertical scroll position of the visual viewport within the document.",
  "scrollx / scrolly": "How far the document is scrolled, updated live as you read.",

  /* ── System theme and UI metrics ──────────────────────────── */
  "scrollbar width": "Width of a classic scrollbar in pixels. Zero means overlay scrollbars, typical of macOS and phones; around 15 to 17 means Windows or Linux.",
  "display refresh rate": "Frames per second, measured by timing animation callbacks. 60 is standard, 120 indicates a recent laptop or gaming monitor.",
  "default font size": "The root font size, which changes if you have raised the browser's default text size for readability.",
  "default font family": "The font stack this page resolves to, which depends on what your system provides.",
  "text size adjust": "Whether the browser will inflate text automatically, a mobile behavior.",
  "caret color": "The resolved text cursor color, which follows the system theme.",
  "emoji/text metric hash": "A digest of how wide your system draws emoji and non-Latin scripts. It shifts with each operating system release, so it dates your OS.",

  /* ── Hardware ─────────────────────────────────────────────── */
  "touch events supported": "Whether touch event handlers exist, which is separate from whether a touchscreen is attached.",
  "gamepads connected": "How many game controllers are plugged in and have been used.",
  "navigator.bluetooth": "Whether the Web Bluetooth API exists. Using it requires a device picker, but its presence identifies the browser.",
  "navigator.usb": "Whether WebUSB exists, which Chromium offers and others refuse.",
  "navigator.serial": "Whether the Web Serial API exists, for talking to devices over serial ports.",
  "navigator.hid": "Whether WebHID exists, for keyboards, controllers and other input devices.",
  "navigator.wakelock": "Whether the page can keep your screen awake.",
  "navigator.vibrate": "Whether the device can be vibrated, effectively a mobile check.",
  "navigator.share": "Whether the native share sheet is available.",
  "navigator.ink": "Whether the Ink API exists, for low-latency stylus drawing.",
  "navigator.virtualkeyboard": "Whether the page can control the on-screen keyboard, a Chromium feature.",
  "navigator.keyboard": "Whether the Keyboard API exists, which can expose your physical layout.",
  "battery.level": "Charge from 0 to 1. Removed from Firefox and Safari after it was used to correlate visitors across sites.",
  "battery.charging": "Whether the device is plugged in.",
  "battery.chargingtime": "Seconds until full, or infinite when not charging.",
  "battery.dischargingtime": "Seconds of battery remaining, or infinite when plugged in.",
  "keyboard layout size": "How many physical keys the layout map describes.",
  "key 'keyq' maps to": "What the physical Q key produces. 'a' means an AZERTY layout, which usually means France or Belgium.",
  "key 'keya' maps to": "What the physical A key produces. 'q' indicates AZERTY.",
  "key 'keyz' maps to": "What the physical Z key produces. 'w' indicates AZERTY, 'y' indicates QWERTZ and therefore German-speaking Europe.",
  "key 'semicolon' maps to": "What the semicolon key produces, which varies across Nordic and Central European layouts.",
  "xr.issessionsupported('immersive-vr')": "Whether a VR headset session could start, which means a headset is attached.",
  "xr.issessionsupported('immersive-ar')": "Whether augmented reality is supported, typical of phones and headsets.",
  "xr.issessionsupported('inline')": "Whether inline XR content can render, supported broadly and therefore less revealing.",

  /* ── Benchmarks and thermals ──────────────────────────────── */
  "float math (9m ops)": "Time to run nine million transcendental operations. A direct measure of single-core speed.",
  "typed array fill + sort (1m)": "Time to fill and sort a million doubles, which exercises memory bandwidth rather than raw arithmetic.",
  "sha-256 of 1 mb": "Time to hash a megabyte using the browser's native crypto, which is hardware-accelerated on modern chips.",
  "composite score": "The three timings combined. Higher is faster, and the value clusters tightly by processor model.",
  "logical cores": "Core count again, alongside the timings it helps explain.",
  "js heap limit": "The maximum heap the JavaScript engine will allocate, which varies by platform and device memory.",
  "drift across runs": "How much slower the last run was than the first. Sustained slowdown means thermal or power limiting.",
  "fastest run": "The best time recorded, closest to the machine's true capability.",
  "slowest run": "The worst time recorded, reflecting contention or throttling.",
  "compute pressure api": "Whether the browser reports processor load state to the page.",
  "current cpu pressure": "The reported load state: nominal, fair, serious or critical.",
  "known pressure sources": "Which pressure sources this browser exposes, currently processor load.",

  /* ── Audio ────────────────────────────────────────────────── */
  audiocontext: "Whether the Web Audio API is available at all.",
  samplerate: "The output device's sample rate in hertz. 44100 and 48000 are both common and the value follows the actual hardware.",
  state: "Whether audio is running or suspended. Browsers suspend it until you interact with the page.",
  baselatency: "Processing latency the browser adds, which reflects the audio driver in use.",
  outputlatency: "Estimated total delay before sound reaches your ears, a property of the physical device.",
  "destination.maxchannelcount": "How many output channels the device supports. Above two means surround hardware.",
  "destination.channelcount": "Channels currently in use, normally stereo.",
  "destination.channelinterpretation": "How the browser maps channels when counts differ.",
  "listener present": "Whether the spatial audio listener exists, part of 3D audio support.",
  "speechsynthesis voices": "How many text-to-speech voices are installed, which varies sharply by operating system and installed language packs.",
  "voice list": "The voices themselves. The set, and which is default, is strongly tied to your OS version and locales.",

  /* ── Decode capability ────────────────────────────────────── */
  "getinstalledrelatedapps()": "Detects whether a matching native or installed web app is present, letting a site know what you have installed.",

  /* ── Devices ──────────────────────────────────────────────── */
  "devices total": "How many media devices are attached in total.",
  audioinput: "Microphone count. Visible without permission; names stay hidden until you grant access.",
  audiooutput: "Speaker and headphone count, which separates a laptop from a desk setup.",
  videoinput: "Camera count, including virtual cameras installed by conferencing software.",
  getsupportedconstraints: "Which capture settings this browser can negotiate, such as resolution or echo cancellation.",
  getdisplaymedia: "Whether screen capture is available to ask for.",

  /* ── Network ──────────────────────────────────────────────── */
  "navigator.online": "Whether a network interface is up. It does not mean the internet is reachable.",
  "connection.effectivetype": "A speed class, not a medium. The browser times your requests and files the result under slow-2g, 2g, 3g or 4g. 4g is the fastest of the four, and it says nothing about whether you are on wi-fi or a phone network.",
  "connection.type": "The physical connection type where the browser exposes it, such as wifi or cellular.",
  "connection.downlink": "Estimated bandwidth in megabits per second, rounded for privacy.",
  "connection.downlinkmax": "Theoretical maximum for the underlying technology, rarely populated.",
  "connection.rtt": "Estimated round-trip time, rounded to 25 ms. Higher values suggest distance or a congested link.",
  "connection.savedata": "Whether you have asked for reduced data usage.",
  "webrtc local candidates": "Network addresses gathered for a peer connection. Browsers now usually substitute a random .local name, which is why a real LAN address rarely appears.",

  /* ── Preferences ──────────────────────────────────────────── */
  "prefers-color-scheme": "Your system light or dark setting, shared with every site you visit.",
  "prefers-reduced-motion": "Whether you have asked the system to minimize animation, often for vestibular reasons.",
  "prefers-reduced-transparency": "Whether you have asked for less transparency in the interface.",
  "prefers-reduced-data": "Whether you have asked for lighter pages, usually because data costs money.",
  "prefers-contrast": "Whether you have asked for more or less contrast, an accessibility setting visible to every page.",
  "forced-colors": "Whether a high-contrast mode is overriding page colors entirely.",
  "inverted-colors": "Whether the system is inverting colors, an accessibility setting.",
  "color-gamut": "The widest color space your display can show: sRGB, P3 or Rec. 2020.",
  "dynamic-range": "Whether the display and browser can show high dynamic range content.",
  "video-dynamic-range": "The same question for video specifically, which some devices answer differently.",
  monochrome: "Bits per pixel on a monochrome display. Zero means a normal color screen.",
  pointer: "Precision of the primary input: fine for a mouse, coarse for a finger, none for keyboard-only.",
  "any-pointer": "The most precise input available, which can differ from the primary one on a touchscreen laptop.",
  hover: "Whether the primary input can hover, which distinguishes a mouse from a finger.",
  "any-hover": "Whether any attached input can hover.",
  "display-mode": "How the page is displayed: in a browser tab, installed as an app, or fullscreen.",
  orientation: "Whether the viewport is currently portrait or landscape.",
  scripting: "Whether JavaScript is enabled. The CSS probes on this page use this to record a scriptless visit.",
  update: "How quickly the display can repaint: fast for screens, slow for e-ink, none for print.",
  "overflow-block": "How content overflows vertically: scrolling for screens, paged for print and e-readers.",
  "overflow-inline": "Whether horizontal overflow can scroll.",
  grid: "Whether the device is a character grid terminal rather than a bitmap screen.",
  "print media": "Whether the page is currently being formatted for print.",
  "resolution (dppx)": "Display density in dots per CSS pixel, matched against common values.",

  /* ── Locale and time ──────────────────────────────────────── */
  "intl timezone": "Your timezone as an IANA name. Handed over with no permission, and enough to place you in a region.",
  "intl locale": "The full locale the browser resolved, combining language and region.",
  calendar: "Which calendar system your locale uses, such as gregory or buddhist.",
  numberingsystem: "Which digits your locale uses, such as latn or arab.",
  hourcycle: "Whether you see 12- or 24-hour time, which correlates with region.",
  "gettimezoneoffset()": "Minutes between your clock and UTC, positive when behind.",
  "offset in january": "Your UTC offset in winter.",
  "offset in july": "Your UTC offset in summer. Comparing the two detects daylight saving.",
  "observes dst": "Whether your timezone shifts seasonally, which excludes large parts of the world.",
  "client clock (iso)": "Your machine's clock in UTC, updating as you read.",
  "client clock (local)": "Your clock as your system formats it, including its timezone abbreviation.",
  "date.now()": "Milliseconds since 1970 on your machine. Drift against the server is itself a weak identifier.",
  "performance.timeorigin": "When this page's timing clock started, which is the moment navigation began.",
  "session age at collection": "How long the page had been open when these values were read.",
  "number format sample": "How your locale formats a large number, exposing its grouping and decimal separators.",
  "currency sample": "How your locale renders currency, including symbol placement.",
  "date format sample": "Your locale's date order, which differs sharply between regions.",
  "time format sample": "Your locale's time format, including whether it uses a 24-hour clock.",
  "collator resolved": "How your locale sorts text, including case and accent sensitivity.",
  "locale.weekinfo.firstday": "Which day your locale starts the week on: 1 for Monday, 7 for Sunday.",
  "locale.weekinfo.weekend": "Which days your locale treats as the weekend, which varies by country.",
  "locale.hourcycles": "Hour cycles your locale accepts.",
  "locale.timezones": "Timezones associated with your locale's region.",
  "intl.supportedvaluesof('timezone')": "How many timezones this browser build knows, which tracks its ICU data version.",
  "intl.supportedvaluesof('currency')": "How many currencies this build knows, another version signal.",

  /* ── Document ─────────────────────────────────────────────── */
  "location.href": "The full URL of this page, including any query string.",
  "location.protocol": "Whether the page loaded over HTTP or HTTPS.",
  "location.host": "Hostname and port as requested.",
  "location.hostname": "Hostname alone. Here it decides which origin the third-party frame uses.",
  "location.port": "The port this page was served on.",
  "location.pathname": "The path portion of the URL.",
  "location.search": "The query string, a common place for tracking parameters such as utm_source or fbclid.",
  "location.hash": "The fragment after the hash, which is never sent to the server.",
  origin: "The scheme, host and port that together define this page's security boundary.",
  "document.referrer": "The page you came from, as visible to scripts.",
  "document.title": "The page title, which is also what appears in your history.",
  "document.characterset": "The character encoding in use.",
  "document.contenttype": "The MIME type this document was served as.",
  "document.compatmode": "Whether the page renders in standards mode or quirks mode.",
  "document.readystate": "How far loading has progressed.",
  "document.visibilitystate": "Whether this tab is in the foreground. Updates the moment you switch tabs.",
  "document.hasfocus()": "Whether the page currently has keyboard focus, which reveals when you click away.",
  "document.designmode": "Whether the whole document is editable.",
  "document.lastmodified": "The document's last-modified time, from the response or the current time.",
  "document.cookie count": "How many cookies are visible to scripts, which excludes HttpOnly ones.",
  "document.cookie names": "The script-visible cookie names.",
  "history.length": "How many entries are in this tab's session history. A large number means a long browsing session in this tab.",
  "history.scrollrestoration": "Whether the browser restores scroll position on back navigation.",
  "window.name": "A value that survives navigation within the tab, including across sites, which is why it appears in the respawn demonstration.",
  "is framed (top !== self)": "Whether this page is inside a frame. Tracking scripts check this to know if they are the embedded party.",
  "window.opener present": "Whether another page opened this one and kept a reference.",
  "issecurecontext": "Whether the page counts as secure. Localhost qualifies, which is why client hints work here.",
  "crossoriginisolated": "Whether the page is isolated enough to use shared memory and precise timers.",
  "document.fullscreenenabled": "Whether fullscreen is permitted in this context.",
  activeelement: "Which element currently has keyboard focus.",

  /* ── Storage ──────────────────────────────────────────────── */
  "storage.quota": "How much this origin is allowed to store. The figure is derived from free disk space, which makes it unexpectedly personal.",
  "storage.usage": "How much this origin currently stores.",
  "usage / quota": "The proportion consumed so far.",
  "usagedetails.caches": "Bytes held in Cache Storage, including the identifier this page wrote there.",
  "usagedetails.serviceworkerregistrations": "Bytes held by registered service workers.",
  "storage.persisted()": "Whether storage is exempt from automatic eviction. Persistent storage survives cleanup that would otherwise clear it.",
  "localstorage available": "Whether localStorage can be used. Private windows sometimes restrict it, which is one way private mode is detected.",
  "localstorage items": "How many keys this origin has in localStorage.",
  "localstorage keys": "The key names, which show what the site is keeping about you.",
  "sessionstorage available": "Whether sessionStorage works in this context.",
  "sessionstorage items": "How many keys exist for this tab only.",
  "sessionstorage keys": "Names of the per-tab keys.",
  "indexeddb available": "Whether the database API exists. Its behavior under private browsing is a classic incognito tell.",
  "indexeddb databases": "Databases this origin has created, including the one holding the respawn identifier.",
  "cachestorage keys": "Named caches this origin holds.",
  "cookiestore entries": "Cookies visible through the newer asynchronous cookie API.",
  "service workers registered": "How many background workers this origin has installed.",
  "document.hasstorageaccess()": "Whether this document has unpartitioned storage access, the mechanism that governs embedded third parties.",

  /* ── Performance ──────────────────────────────────────────── */
  "navigation.type": "How you arrived: a fresh navigation, a reload, or back-forward.",
  "navigation.redirectcount": "How many redirects happened before this page, which can expose tracking hops.",
  nexthopprotocol: "The protocol that actually delivered this page, such as http/1.1 or h2.",
  "redirect time": "Time spent following redirects.",
  "dns lookup": "Time spent resolving the hostname. Zero usually means it was cached.",
  "tcp connect": "Time to establish the connection, which correlates with distance to the server.",
  "tls negotiation": "Time spent on the encryption handshake.",
  "request → first byte": "Time from sending the request to the first byte of response, the standard measure of server latency.",
  "response download": "Time spent receiving the response body.",
  "dom interactive": "When the document became interactive, which reflects your machine's parsing speed.",
  domcontentloaded: "When the initial document had been fully parsed.",
  "load event end": "When everything, including images and frames, had finished loading.",
  transfersize: "Bytes actually transferred, including headers. Near-zero means it came from cache.",
  encodedbodysize: "Compressed size of the response body.",
  decodedbodysize: "Uncompressed size, which against the encoded size shows compression effectiveness.",
  deliverytype: "How the response was delivered: 'cache' if served from cache, 'navigational-prefetch' if speculatively fetched, empty otherwise.",
  activationstart: "Non-zero only when a page was prerendered before you asked for it, revealing speculative loading.",
  "first-paint": "When the browser first painted anything at all.",
  "first-contentful-paint": "When the first real content appeared, which is what a visitor perceives as speed.",
  "resource entries": "How many separate resources this page loaded.",
  "performance.now() precision": "The finest measurable time step. Browsers coarsen this deliberately to blunt timing attacks.",
  "memory.jsheapsizelimit": "Maximum JavaScript heap, which varies with device memory. Chromium only.",
  "memory.totaljsheapsize": "Heap currently allocated.",
  "memory.usedjsheapsize": "Heap currently in use by this page.",

  /* ── Interaction ──────────────────────────────────────────── */
  "pointermove events": "How many pointer movements this page has recorded since it loaded.",
  "last pointer position": "Where your cursor was most recently, in page coordinates.",
  "last pointer characteristics": "The pointer type and its contact geometry, which distinguishes a mouse from a finger or a stylus.",
  "max pointer pressure": "Hardest press recorded. Non-zero implies a pressure-sensitive stylus or touchscreen.",
  "click events": "How many times you have clicked.",
  "keydown events": "How many keys you have pressed. The count alone, without the keys, still describes your activity.",
  "scroll events": "How many scroll events have fired.",
  "focus/blur events": "How often this window has gained or lost focus, which reveals switching to other applications.",
  "visibility changes": "How often you have switched away from this tab and back.",
  "resize events": "How often the window has been resized.",
  deviceorientation: "The most recent orientation reading, where sensors exist and are permitted.",
  devicemotion: "The most recent acceleration reading, including the reporting interval, which varies by device.",
  "time on page": "How long this page has been open, updating as you read.",
  "movement samples held": "How many cursor positions are currently buffered for the movement analysis.",
  "mean pointer speed": "Average cursor speed in pixels per second, part of the movement signature.",
  "speed variability": "How much your speed fluctuates, which is personal and fairly stable.",
  "mean acceleration": "How abruptly your cursor changes speed. Human movement accelerates differently from scripted movement.",
  "path curvature": "How curved your cursor path is. People arc; automation moves in straight lines.",

  /* ── Cross-tab ────────────────────────────────────────────── */
  broadcastchannel: "Whether same-origin pages can message each other directly.",
  "other tabs of this site open": "How many other tabs of this site answered a broadcast just now.",
  "this tab's temporary id": "A random label for this tab, used only to recognize its own replies.",
  sharedworker: "Whether a single worker can be shared across tabs, another way to link them.",
  "web locks api": "Whether the browser offers cross-tab locks, which can also be used to count tabs.",
  "locks currently held": "Locks held and queued right now across all tabs of this site.",
  "storage events": "Writing to localStorage notifies every other tab, a long-standing cross-tab channel.",

  /* ── Worker cross-check ───────────────────────────────────── */
  "worker::useragent": "The user agent as seen inside a Web Worker. Tools that patch only the page disagree here.",
  "worker::platform": "The platform string inside the worker, compared against the page's.",
  "worker::language": "The primary language inside the worker.",
  "worker::languages": "The language list inside the worker.",
  "worker::hardwareconcurrency": "Core count inside the worker, a common thing to fake on the page and forget here.",
  "worker::devicememory": "Device memory as the worker sees it.",
  "worker::online": "Connectivity as the worker sees it.",
  "worker::vendor": "Vendor string, which workers do not expose at all — absence here is expected, not suspicious.",
  "worker::product": "Product string inside the worker.",
  "worker::appversion": "Version string inside the worker.",
  "worker::timezone": "The timezone the worker resolves, which catches page-level timezone spoofing.",
  "worker::locale": "The locale the worker resolves.",
  "worker::uadataplatform": "Client-hint platform inside the worker.",
  "worker::uadatamobile": "Client-hint mobile flag inside the worker.",
  "worker offscreencanvas": "Whether the worker can render graphics off the main thread, which allows fingerprinting without touching the page.",
  "worker canvas byte size": "Size of an image the worker rendered, which varies with the same rasterization differences as canvas fingerprinting.",
  "worker webgl renderer": "The GPU string as reported inside a worker, compared against the page's.",

  /* ── Granted probes ───────────────────────────────────────── */
  latitude: "Your latitude from the operating system's location service.",
  longitude: "Your longitude. Together with latitude this is a building, not a city.",
  accuracy: "Radius of uncertainty in meters. Single digits mean GPS or a dense wifi survey.",
  altitude: "Height above sea level where the device can measure it.",
  altitudeaccuracy: "Uncertainty of the altitude figure.",
  heading: "Direction of travel in degrees, available when moving.",
  speed: "Ground speed in meters per second, available when moving.",
  timestamp: "When the position was fixed.",
  "clipboard length": "How many characters your clipboard held.",
  "clipboard contents": "What you last copied, handed over in full on approval.",
  "clipboard item types": "The formats on the clipboard, such as plain text, HTML or an image.",
  "fonts installed": "The real number of installed typefaces, straight from the operating system rather than estimated.",
  families: "How many distinct font families those faces belong to.",
  "full list": "Every installed face by name — for many people a unique set, and a fair inventory of installed software.",
  "screens attached": "How many displays are connected.",
  "current screen label": "The manufacturer label of the display this window is on.",
  "user state": "Whether you are active at the keyboard or idle.",
  "screen state": "Whether your screen is locked, reported continuously in the background.",
  "orientation sample": "A single reading of device tilt in three axes.",
  "motion sample": "A single acceleration reading. Sensor calibration noise is unique to the individual handset and survives every browser reset.",
  method: "How the detection was performed, and how reliable it is.",

  /* ── Typing biometrics ────────────────────────────────────── */
  "characters measured": "How many keystrokes contributed to the measurement.",
  "mean key hold (dwell)": "Average time a key stays down. Stable per person and largely unconscious.",
  "hold consistency (σ)": "Variation in hold times. Very low values suggest synthetic input rather than a human.",
  "mean gap between keys (flight)": "Average time between releasing one key and pressing the next, shaped by your familiarity with the phrase.",
  "gap consistency (σ)": "Variation in those gaps, one of the stronger individual signals.",
  "typing speed": "Words per minute for this attempt.",
  "stored profile existed": "Whether an earlier rhythm was already saved in this browser.",
  "distance from stored profile": "How far this attempt sits from the stored rhythm. Lower means more likely the same person.",
  verdict: "The match conclusion, using the same logic fraud systems apply to decide whether the expected human is present.",
};

/** Platform APIs listed in the feature matrix: what each one does. */
export const FEATURE_NOTES: Record<string, string> = {
  ServiceWorker: "Lets a site run a script in the background that intercepts its network requests, even after the tab closes.",
  WebSocket: "A persistent two-way connection, used for chat, live data and telemetry.",
  WebTransport: "A newer low-latency transport over HTTP/3, replacing WebSocket for real-time use.",
  WebRTC: "Peer-to-peer audio, video and data. Setting up a connection enumerates your network addresses.",
  WebGL2: "The second-generation 3D graphics API, which exposes more about the GPU than WebGL 1.",
  WebGPU: "The modern graphics and compute API. Its adapter report names the GPU vendor and architecture.",
  WebXR: "Virtual and augmented reality sessions, which reveal whether a headset is attached.",
  WebAuthn: "Passkeys and security keys. Which authenticators exist is itself revealing.",
  "WebCrypto (subtle)": "Native cryptography, used here to time a SHA-256 hash of a megabyte.",
  "crypto.randomUUID": "Native unique identifier generation, added in 2021, which dates the browser.",
  "Credential Management": "Lets sites store and retrieve sign-in credentials from the browser.",
  "Payment Request": "The native payment sheet. Its availability correlates with the platform and configured cards.",
  "Push API": "Server-sent messages that arrive even when the site is closed.",
  Notification: "System notifications, which require permission but whose current state is readable without prompting.",
  Geolocation: "Access to the operating system's location service, gated by a prompt.",
  "Clipboard API": "Programmatic clipboard access. Reading requires permission; writing often does not.",
  "File System Access": "Direct read and write access to files you pick, offered by Chromium only.",
  EyeDropper: "Lets a page sample a color from anywhere on your screen, Chromium only.",
  "Contact Picker": "Access to the device address book after you choose entries, mobile Chromium only.",
  "Idle Detection": "Reports whether you are at the keyboard and whether the screen is locked.",
  "Screen Wake Lock": "Keeps the display awake while the page is open.",
  "Window Management": "Enumerates every attached display and their arrangement, behind a permission.",
  "Web Share": "Opens the native share sheet, typical of mobile platforms.",
  "Web Share (files)": "Whether files can be shared through that sheet.",
  "Background Fetch": "Downloads that continue after the tab closes.",
  "Periodic Sync": "Lets a site wake periodically in the background to refresh itself.",
  "Web Locks": "Coordination between tabs of the same site, which can also count them.",
  "Broadcast Channel": "Direct messaging between same-origin tabs.",
  SharedWorker: "One worker shared by every tab of a site, another way to link them.",
  OffscreenCanvas: "Rendering off the main thread, which allows canvas fingerprinting inside a worker.",
  ImageCapture: "Still photo capture from a camera stream, with access to camera settings.",
  MediaRecorder: "Recording audio and video streams in the browser.",
  "Picture-in-Picture": "Floating video outside the page.",
  "Speech Recognition": "Speech-to-text, which on some platforms sends audio to a remote service.",
  "Speech Synthesis": "Text-to-speech. The installed voice list is strongly tied to your operating system.",
  "Sensors (Accelerometer)": "The generic sensor API for motion hardware.",
  DeviceOrientation: "Tilt events, whose calibration noise is unique to an individual device.",
  "Ambient Light": "Light-level readings, removed from most browsers because they leaked surroundings.",
  Gamepad: "Game controller input, which enumerates attached controllers once used.",
  "Pointer Lock": "Hides and captures the cursor, used by games.",
  Fullscreen: "Whether the page may take over the screen.",
  "Resize/Intersection Observer": "Efficient notification of element size and visibility changes.",
  "Reporting Observer": "Access to browser-generated deprecation and intervention reports.",
  "Performance Observer": "Access to detailed timing entries, which this page uses for its load breakdown.",
  "Navigation API": "The modern navigation interface, currently Chromium only.",
  "View Transitions": "Animated transitions between page states, a recent addition.",
  "Popover API": "Native popovers, shipped across browsers in 2023 and 2024.",
  "Dialog element": "Native modal dialogs.",
  "CSS Houdini (paintWorklet)": "Programmatic painting in CSS, Chromium only.",
  "container queries": "Styling based on a container's size rather than the viewport, from 2023.",
  "CSS :has()": "The parent selector, widely shipped in 2023 and a sharp version marker.",
  "CSS nesting": "Native nested style rules, from 2023.",
  "color-mix()": "Color blending in CSS, from 2023.",
  "oklch()": "Perceptually uniform color, from 2023. Its presence dates the engine.",
  "backdrop-filter": "Blur and other effects behind an element.",
  "Trusted Types": "A defense against DOM-based injection, Chromium only.",
  "Topics API": "Google's interest-based advertising signal, which reports coarse topics inferred from your browsing.",
  "Attribution Reporting": "Ad conversion measurement without cross-site identifiers.",
  "Private State Tokens": "Anti-fraud tokens that vouch for you without identifying you.",
  "Protected Audience (FLEDGE)": "On-device ad auctions, part of the Privacy Sandbox.",
  "Storage Access API": "Lets an embedded site request access to its own unpartitioned storage.",
  "Federated Credential (FedCM)": "Browser-mediated federated sign-in, replacing third-party cookies for login.",
};

/** Browser permissions: what granting each one allows. */
export const PERMISSION_NOTES: Record<string, string> = {
  geolocation: "Position from the operating system's location service, usually accurate to a few meters.",
  notifications: "Messages delivered to your system notification center, including when the site is closed.",
  camera: "Video capture, plus the hardware names and stable identifiers of every camera.",
  microphone: "Audio capture, plus the names and identifiers of every microphone.",
  "clipboard-read": "Whatever you last copied, read in full with no further indication.",
  "clipboard-write": "Placing content on your clipboard.",
  "persistent-storage": "Exemption from automatic storage cleanup, so stored identifiers survive longer.",
  midi: "Access to connected MIDI instruments, including system-exclusive messages.",
  "background-sync": "Deferred work that runs once connectivity returns.",
  push: "Server-initiated messages delivered through the browser vendor's push service.",
  accelerometer: "Raw motion readings, whose calibration noise identifies the physical device.",
  gyroscope: "Rotation readings from the device's gyroscope.",
  magnetometer: "Compass heading, which combined with position is highly revealing.",
  "ambient-light-sensor": "Light levels around the device, which can imply whether you are indoors.",
  "payment-handler": "Lets the site act as a payment method in the browser's payment sheet.",
  "screen-wake-lock": "Keeps the screen awake.",
  "local-fonts": "The complete installed font list, which is close to a software inventory.",
  "window-management": "Every attached display, its resolution, position and manufacturer label.",
  "idle-detection": "Continuous reporting of whether you are at the keyboard and whether the screen is locked.",
  "speaker-selection": "Choosing which audio output device is used.",
  "storage-access": "Unpartitioned storage for an embedded third party, which restores cross-site recognition.",
  "top-level-storage-access": "The same, requested by the top-level site on an embed's behalf.",
  bluetooth: "Talking to nearby Bluetooth devices you select.",
  nfc: "Reading and writing NFC tags.",
  "display-capture": "Capturing a screen, window or tab.",
  "captured-surface-control": "Scrolling and zooming a captured tab, an extension of screen sharing.",
  "Notification.permission": "The current notification permission, readable without prompting — which also tells a site how cautious you are.",
};

/** FingerprintJS entropy sources: what each one actually samples. */
export const COMPONENT_NOTES: Record<string, string> = {
  userAgentData: "Structured client hints, including platform and brand list.",
  fonts: "Which of a fixed set of typefaces resolve, measured by text width.",
  domBlockers: "Applies selectors from real ad-blocking filter lists and sees which elements disappear.",
  fontPreferences: "Measures text under several default font settings, capturing your default font sizes and zoom.",
  audio: "A digest of an inaudible tone rendered through a compressor.",
  screenFrame: "The space between the screen and its usable area, which describes where your dock or taskbar sits.",
  canvas: "Pixels from a fixed drawing, capturing font rasterization and anti-aliasing differences.",
  osCpu: "Firefox's oscpu string. Absent elsewhere, so its presence alone is a signal.",
  languages: "Your language list in preference order.",
  colorDepth: "Bits per pixel the display reports.",
  deviceMemory: "Approximate RAM, rounded to a power of two.",
  screenResolution: "Display dimensions, sorted so orientation changes do not alter the value.",
  hardwareConcurrency: "Logical processor count.",
  timezone: "Your IANA timezone name.",
  sessionStorage: "Whether per-tab storage works, which private modes sometimes restrict.",
  localStorage: "Whether persistent local storage works.",
  indexedDB: "Whether the database API works, a classic private-browsing tell.",
  openDatabase: "Whether the removed WebSQL API still exists, which dates the browser precisely.",
  cpuClass: "A legacy Internet Explorer property, absent in every modern browser.",
  platform: "The navigator platform string, cross-checked against other platform signals.",
  plugins: "The plugin list, now a fixed set in Chromium and empty in Firefox.",
  touchSupport: "Maximum touch points and whether touch events exist.",
  vendor: "The navigator vendor string, one of the cleanest engine tells.",
  vendorFlavors: "Which vendor-specific globals exist, such as window.chrome or window.safari.",
  cookiesEnabled: "Whether cookies can be written.",
  colorGamut: "The widest color space the display supports.",
  invertedColors: "Whether the system inverts colors, an accessibility setting.",
  forcedColors: "Whether a high-contrast mode is overriding page colors.",
  monochrome: "Bit depth of a monochrome display; zero on ordinary color screens.",
  contrast: "Your contrast preference, mapped to a number.",
  reducedMotion: "Whether you have asked the system to minimize animation.",
  reducedTransparency: "Whether you have asked for reduced transparency.",
  hdr: "Whether the display supports high dynamic range.",
  math: "Results of transcendental math functions, which differ in the last bits between engines and processors.",
  pdfViewerEnabled: "Whether the browser renders PDFs itself.",
  architecture: "Reads the byte layout of a NaN value, which exposes the processor's floating-point behavior.",
  applePay: "Whether Apple Pay can be offered, which implies an Apple device and its configuration.",
  privateClickMeasurement: "Whether Safari's ad attribution attributes exist on links.",
  audioBaseLatency: "The audio stack's processing latency, which reflects the driver in use.",
  dateTimeLocale: "How your locale formats dates and times.",
  webGlBasics: "GPU vendor, renderer and core parameters.",
  webGlExtensions: "Which WebGL extensions the driver offers, a long and very specific list.",
};

/** CSS system colors: each keyword names a different part of the OS theme. */
export const SYSTEM_COLOR_NOTES: Record<string, string> = {
  AccentColor: "The accent color you chose in system settings — a direct, deliberate personal preference, readable by any page.",
  AccentColorText: "The text color the system draws on top of your accent color.",
  ActiveText: "The color of a link while it is being clicked.",
  ButtonBorder: "The border color of a native button, which differs between operating systems and themes.",
  ButtonFace: "The background of a native button, one of the clearest indicators of light or dark mode.",
  ButtonText: "The label color on a native button.",
  Canvas: "The default document background the system expects, which reveals the OS theme even when a page overrides it.",
  CanvasText: "The default text color the system expects.",
  Field: "The background of a text input as the system draws it.",
  FieldText: "The text color inside an input.",
  GrayText: "The color the system uses for disabled text.",
  Highlight: "The background of selected text. Its hue often follows your accent color.",
  HighlightText: "The text color inside a selection.",
  LinkText: "The system's unvisited link color.",
  Mark: "The background the system uses for highlighted text.",
  MarkText: "The text color on highlighted text.",
  SelectedItem: "The background of a selected item in a menu or list.",
  SelectedItemText: "The text color of a selected item.",
  VisitedText: "The system's visited link color.",
};

/** Each CSS-only probe: what its rule tests and what a match reveals. */
export const CSS_PROBE_NOTES: Record<string, string> = {
  "Dark mode is on": "A rule under `prefers-color-scheme: dark` fetched its image, so the server knows your system theme without any script.",
  "Light mode is on": "The light-mode rule matched, which tells the server your theme setting directly.",
  "Reduced motion requested": "You have asked the system to minimize animation, an accessibility preference sent here with no prompt.",
  "Reduced transparency requested": "You have asked the system to reduce transparency effects.",
  "Higher contrast requested": "You have asked for increased contrast, which most people never enable and which therefore stands out.",
  "Lower contrast requested": "You have asked for reduced contrast, a rare setting and so a strong signal.",
  "Forced colors active (high-contrast mode)": "A system high-contrast mode is overriding page colors, common among users with low vision.",
  "Colors inverted": "The system is inverting colors, an accessibility setting.",
  "Data saving requested": "You have asked for reduced data usage, which often means a metered or expensive connection.",
  "Wide color display (P3)": "Your display covers the P3 gamut, typical of Apple hardware and recent high-end screens.",
  "Very wide color display (Rec. 2020)": "Your display claims Rec. 2020 coverage, which is rare and therefore identifying.",
  "HDR-capable display": "The display and browser can show high dynamic range content.",
  "Monochrome display": "A grayscale display, unusual enough to be highly distinguishing.",
  "Standard-density screen (1×)": "One physical pixel per CSS pixel, typical of older or cheaper monitors.",
  "Retina screen (2×)": "Two physical pixels per CSS pixel, typical of Apple laptops and most modern phones.",
  "High-density screen (3×)": "Three physical pixels per CSS pixel, typical of flagship phones.",
  "Portrait orientation": "The viewport is taller than it is wide.",
  "Landscape orientation": "The viewport is wider than it is tall.",
  "Window narrower than 640px": "Your window falls in the narrowest bucket, which usually means a phone.",
  "Window 640–1023px": "A small window or a tablet.",
  "Window 1024–1439px": "A typical laptop window.",
  "Window 1440–1919px": "A large laptop or a small desktop monitor.",
  "Window 1920px or wider": "A wide desktop monitor.",
  "Window shorter than 800px": "A short viewport, which combined with width narrows the device further.",
  "Window 800px tall or more": "A tall viewport.",
  "Mouse or trackpad": "The primary input is precise, so this is a computer rather than a touchscreen.",
  Touchscreen: "The primary input is a finger, so this is a phone or tablet.",
  "Can hover": "The input can hover, which effectively confirms a pointing device.",
  "Cannot hover": "No hover capability, which confirms touch-only input.",
  "Installed as an app": "The page is running as an installed application rather than in a browser tab.",
  "Fast-updating display": "The display refreshes quickly, ruling out e-ink and print.",
  "JavaScript is DISABLED": "This rule only matches when scripting is off. Disabling JavaScript is itself recorded, and everything else in this table was still collected.",
  "JavaScript is enabled": "Scripting is on, which the server learns from CSS regardless of what the scripts do.",
  "Supports oklch() colors": "The engine supports perceptually uniform color, shipped in 2023, which dates the browser.",
  "Supports :has()": "The parent selector, widely shipped in 2023 — a sharp version marker.",
  "Supports CSS nesting": "Native nesting, from 2023.",
  "Supports backdrop-filter": "Backdrop effects, supported across engines but at different times.",
  "Supports container queries": "Container queries, from 2023.",
  "WebKit on touch (iOS Safari)": "A property only WebKit exposes on touch devices, which identifies iOS Safari without any script.",
  "Gecko engine (Firefox)": "A Mozilla-only property, which identifies Firefox from CSS alone.",
  "Apple Pay button style (Safari)": "A Safari-only appearance value, which identifies an Apple browser.",
  "WebKit/Blink font smoothing": "A property Chromium and WebKit share and Firefox does not.",
};

/** Repeated benchmark runs mean different things in sequence. */
export const RUN_NOTES: Record<string, string> = {
  "benchmark run 1": "The first pass, taken cold. It reflects the machine at its best, before any heat builds up.",
  "benchmark run 2": "The second pass. Still close to peak on a well-cooled machine.",
  "benchmark run 3": "The middle pass, where a thermally constrained laptop usually starts to slow.",
  "benchmark run 4": "The fourth pass, by which point a throttling machine is clearly slower.",
  "benchmark run 5": "The final pass. Compared with the first, it shows how well the machine sustains load.",
};
